###Agregar
POST http://localhost:1234/url/create
Content-Type: application/json

{
"url":"https://www.google.com/search?q=ERR_CONNECTION_REFUSED&rlz=1C1YTUH_esVE1062VE1062&oq=ERR_CONNECTION_REFUSED&gs_lcrp=EgZjaHJvbWUqDggAEEUYJxg7GIAEGIoFMg4IABBFGCcYOxiABBiKBTIHCAEQABiABDIHCAIQABiABDIHCAMQABiABDIHCAQQABiABDIHCAUQABiABDIMCAYQABhDGIAEGIoFMgwIBxAAGEMYgAQYigUyBwgIEAAYgAQyBwgJEAAYgATSAQc3ODFqMGo3qAIIsAIB&sourceid=chrome&ie=UTF-8"
}
###crear
POST http://localhost:1234/register
Content-Type: application/json

{
     "username":"josed",
     "email":"villarroelsaad@gmail.coms",
     "password":"geometry7ss"
}


###Log
POST http://localhost:1234/login
Content-Type: application/json

{
  "username":"jose",
  "password":"geometry7"
}
###Get
GET http://localhost:1234/links/1
Content-Type: application/json

###delete
DELETE http://localhost:1234/delete/1
Content-Type: application/json



